<a href="https://colab.research.google.com/github/JinHeeeKang/Python_DeepLearning/blob/master/RNN-%20SimpleRNN%2CLSTM%2Cseq2seq.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# RNN
- 순환신경망
- simpleRNN_practice

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import SimpleRNN,Dense
from tensorflow.keras.models import Sequential
import numpy as np


In [ ]:
imdb=tf.keras.datasets.imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

17465344/17464789 [==============================] - 0s 0us/step


In [ ]:
word_index = imdb.get_word_index()

1646592/1641221 [==============================] - 0s 0us/step


In [ ]:
id_to_word=dict([(value,key) for key,value in word_index.items()])

In [ ]:
vocab_size = len(word_index)
vocab_size

88584

In [ ]:
word_index = {k:(v+3) for k,v in word_index.items()}
word_index["<PAD>"] = 0 #공백
word_index["<START>"] = 1 #문장 시작
word_index["<UNK>"] = 2 #unknown 정보
word_index["<UNUSED>"] = 3 #사용하지않는 단어

In [ ]:
def decode_review(text):
  return ' '.join([id_to_word.get(i, '?') for i in text])#get() i가 없을때 ?출력 

In [ ]:
train_data[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [ ]:
decode_review(train_data[0])

"the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room and it so heart shows to years of every never going and help moments or of every chest visual movie except her was several of enough more with is now current film as you of mine potentially unfortunately of you than him that with out themselves her get for was camp of you movie sometimes movie that with scary but and to story wonderful that in seeing in character to of 70s musicians with heart had shadows they of here that with her serious to have does when from why what have critics they is you that isn't one will very to as itself with other and in of seen over landed for anyone of and br show's to whether from than out themselves history he name half some br of and odd was two most of mean for 1 any an boat she he should is thought frog but of script you not while history he heart to real at barrel but when from one bit then have t

In [ ]:
len(train_data[0]),len(train_data[1]),len(train_data[2])

(218, 189, 141)

In [ ]:
# train,test확인해서 maxlen 길이 맞추기 
maxlen=0
for data in train_data:
    if len(data)>maxlen:
        maxlen=len(data)

In [ ]:
for data in test_data:
    if len(data)>maxlen:
        maxlen=len(data)

In [ ]:
maxlen

2494

In [ ]:
train_data=tf.keras.preprocessing.sequence.pad_sequences(
    train_data,value=0,padding='pre',maxlen=maxlen
)

In [ ]:
test_data=tf.keras.preprocessing.sequence.pad_sequences(
    test_data,value=0,padding='pre',maxlen=maxlen
)

In [ ]:
len(test_data)

25000

In [ ]:
len(train_data)

25000

In [ ]:
model= Sequential(
    [
    #  tf.keras.layers.Embedding(vocab_size)
    SimpleRNN(units=126,input_shape=(None,maxlen)),# input이 많아서 은닉층(units)도 크게
    Dense(16,activation='relu'),
    Dense(1,activation='sigmoid')
    ]
)

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 126)               330246    
_________________________________________________________________
dense (Dense)                (None, 16)                2032      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 332,295
Trainable params: 332,295
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
train_data=train_data[:,tf.newaxis,:]
test_data=test_data[:,tf.newaxis,:]

In [ ]:
train_data.shape, test_data.shape

((25000, 1, 2494), (25000, 1, 2494))

In [ ]:
#데이터를 3개로 맞춰줘야함
history=model.fit(train_data,train_labels,
                  epochs=20,
                  batch_size=128,
                  validation_split=0.2)

Epoch 1/20
157/157 [==============================] - 1s 5ms/step - loss: 0.7173 - accuracy: 0.5056 - val_loss: 0.7003 - val_accuracy: 0.4950
Epoch 2/20
157/157 [==============================] - 1s 4ms/step - loss: 0.6945 - accuracy: 0.5128 - val_loss: 0.6954 - val_accuracy: 0.4994
Epoch 3/20
157/157 [==============================] - 1s 4ms/step - loss: 0.6921 - accuracy: 0.5135 - val_loss: 0.6952 - val_accuracy: 0.4988
Epoch 4/20
157/157 [==============================] - 1s 4ms/step - loss: 0.6908 - accuracy: 0.5192 - val_loss: 0.6946 - val_accuracy: 0.5070
Epoch 5/20
157/157 [==============================] - 1s 4ms/step - loss: 0.6908 - accuracy: 0.5214 - val_loss: 0.6949 - val_accuracy: 0.5142
Epoch 6/20
157/157 [==============================] - 1s 4ms/step - loss: 0.6902 - accuracy: 0.5292 - val_loss: 0.6950 - val_accuracy: 0.5030
Epoch 7/20
157/157 [==============================] - 1s 4ms/step - loss: 0.6905 - accuracy: 0.5255 - val_loss: 0.6940 - val_accuracy: 0.5062
Epoch 

In [ ]:
#RNN
# model= Sequential(
#     [
#      SimpleRNN(units=16,input_shape=(None,)),
#      Dense(8,activation='relu')
#      Dense(1,activation='??')#풀려는 문제에 따라 달라짐
#     ]
# )

#LSTM
- Long Short-Term Memory
- simpleRNN 보완
- input 데이터가 많을때 중요한 정보가 마지막즈음엔 희석되어 있을 가능성이 크다  
 -> 이건 빼먹지말고 ㅇㅇ단계까지는 유지해라!

# LSTM을 사용한 문장생성
- 애국가

In [ ]:
text='''
동해 물과 백두산이 마르고 닳도록
하느님이 보우하사 우리나라 만세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
남산 위에 저 소나무, 철갑을 두른 듯
바람 서리 불변함은 우리 기상일세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
가을 하늘 공활한데 높고 구름 없이
밝은 달은 우리 가슴 일편단심일세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
이 기상과 이 맘으로 충성을 다하여
괴로우나 즐거우나 나라 사랑하세.
무궁화 삼천리 화려 강산
대한 사람, 대한으로 길이 보전하세.
'''

In [ ]:
import tensorflow as tf

In [ ]:
#특수 문자 제거, 띄어쓰기 기준으로 쪼개기, indexing
t = tf.keras.preprocessing.text.Tokenizer()

In [ ]:
t.fit_on_texts([text])

In [ ]:
vocab_size=len(t.word_index)+1 #빈값을 0으로 해주는데 word_index에 0이 없기때문에 +1해줌
print(vocab_size)

50


In [ ]:
t.word_index

{'가슴': 40,
 '가을': 32,
 '강산': 4,
 '공활한데': 34,
 '괴로우나': 46,
 '구름': 36,
 '기상과': 42,
 '기상일세': 31,
 '길이': 8,
 '나라': 48,
 '남산': 21,
 '높고': 35,
 '다하여': 45,
 '달은': 39,
 '닳도록': 16,
 '대한': 5,
 '대한으로': 7,
 '동해': 12,
 '두른': 26,
 '듯': 27,
 '마르고': 15,
 '만세': 20,
 '맘으로': 43,
 '무궁화': 1,
 '물과': 13,
 '바람': 28,
 '밝은': 38,
 '백두산이': 14,
 '보우하사': 18,
 '보전하세': 9,
 '불변함은': 30,
 '사람': 6,
 '사랑하세': 49,
 '삼천리': 2,
 '서리': 29,
 '소나무': 24,
 '없이': 37,
 '우리': 10,
 '우리나라': 19,
 '위에': 22,
 '이': 11,
 '일편단심일세': 41,
 '저': 23,
 '즐거우나': 47,
 '철갑을': 25,
 '충성을': 44,
 '하느님이': 17,
 '하늘': 33,
 '화려': 3}

In [ ]:
id_to_word=dict([(value,key) for key,value in t.word_index.items()])
id_to_word

{1: '무궁화',
 2: '삼천리',
 3: '화려',
 4: '강산',
 5: '대한',
 6: '사람',
 7: '대한으로',
 8: '길이',
 9: '보전하세',
 10: '우리',
 11: '이',
 12: '동해',
 13: '물과',
 14: '백두산이',
 15: '마르고',
 16: '닳도록',
 17: '하느님이',
 18: '보우하사',
 19: '우리나라',
 20: '만세',
 21: '남산',
 22: '위에',
 23: '저',
 24: '소나무',
 25: '철갑을',
 26: '두른',
 27: '듯',
 28: '바람',
 29: '서리',
 30: '불변함은',
 31: '기상일세',
 32: '가을',
 33: '하늘',
 34: '공활한데',
 35: '높고',
 36: '구름',
 37: '없이',
 38: '밝은',
 39: '달은',
 40: '가슴',
 41: '일편단심일세',
 42: '기상과',
 43: '맘으로',
 44: '충성을',
 45: '다하여',
 46: '괴로우나',
 47: '즐거우나',
 48: '나라',
 49: '사랑하세'}

In [ ]:
# for line in text_index:
#     print(line)

In [ ]:
sequences =list()
for line in text.split('\n'):
    encoded = t.texts_to_sequences([line])[0] #texts_to_sequences 짜잘한 토근 제거해줌
    # print(encoded)
    #[12,13,14,15,16]
    #[12,13]=>[14]
    #[12,13,14]=>[15]
    for i in range(1,len(encoded)):
        sequence =encoded[:i+1]
        sequences.append(sequence)
        # print(sequences)

In [ ]:
maxlen=0
for seq in sequences:
    if len(seq)>maxlen:
        maxlen= len(seq)

In [ ]:
sequences=tf.keras.preprocessing.sequence.pad_sequences(sequences,value=0,maxlen=maxlen)

In [ ]:
sequences[:3]

array([[ 0,  0,  0,  0,  0, 12, 13],
       [ 0,  0,  0,  0, 12, 13, 14],
       [ 0,  0,  0, 12, 13, 14, 15]], dtype=int32)

In [ ]:
X=sequences[:,:-1] 
y=sequences[:,-1] #끝 하나만

In [ ]:
X.shape,y.shape

((62, 6), (62,))

In [ ]:
X[:5]

array([[ 0,  0,  0,  0,  0, 12],
       [ 0,  0,  0,  0, 12, 13],
       [ 0,  0,  0, 12, 13, 14],
       [ 0,  0, 12, 13, 14, 15],
       [ 0,  0,  0,  0,  0, 17]], dtype=int32)

In [ ]:
y[:5]

array([13, 14, 15, 16, 18], dtype=int32)

In [ ]:
#one-hot
y=tf.keras.utils.to_categorical(y,num_classes=vocab_size)

In [ ]:
y[:3]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]], dtype=float32)

모델정의

In [ ]:
# input -> embedding
# LSTM->
# Dense->softmax

In [ ]:
model=tf.keras.models.Sequential(
    [
     tf.keras.layers.Embedding(vocab_size,10),
     tf.keras.layers.LSTM(128),
     tf.keras.layers.Dense(vocab_size,activation='softmax')
    ]
)

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
history=model.fit(X,y,epochs=200)

Epoch 1/200
2/2 [==============================] - 0s 4ms/step - loss: 3.9109 - accuracy: 0.0645
Epoch 2/200
2/2 [==============================] - 0s 3ms/step - loss: 3.9054 - accuracy: 0.0645
Epoch 3/200
2/2 [==============================] - 0s 3ms/step - loss: 3.8998 - accuracy: 0.0645
Epoch 4/200
2/2 [==============================] - 0s 3ms/step - loss: 3.8930 - accuracy: 0.0645
Epoch 5/200
2/2 [==============================] - 0s 3ms/step - loss: 3.8860 - accuracy: 0.0645
Epoch 6/200
2/2 [==============================] - 0s 3ms/step - loss: 3.8755 - accuracy: 0.0645
Epoch 7/200
2/2 [==============================] - 0s 2ms/step - loss: 3.8641 - accuracy: 0.0645
Epoch 8/200
2/2 [==============================] - 0s 4ms/step - loss: 3.8478 - accuracy: 0.0645
Epoch 9/200
2/2 [==============================] - 0s 2ms/step - loss: 3.8264 - accuracy: 0.0645
Epoch 10/200
2/2 [==============================] - 0s 3ms/step - loss: 3.8002 - accuracy: 0.0645
Epoch 11/200
2/2 [===========

- 학습된 모델
- 현재 input (단어 하나 or 시작점 표시)
- 생성하려는 문장의 길이
- 걀과를 단어로 변환해주기 위한 TOKENIZER 함수화

In [ ]:
X[:2]

array([[ 0,  0,  0,  0,  0, 12],
       [ 0,  0,  0,  0, 12, 13]], dtype=int32)

In [ ]:
model.predict(X[:2])

array([[2.07552057e-05, 2.58821274e-05, 6.64642919e-03, 2.55750562e-03,
        2.13442356e-04, 3.15386606e-05, 4.27073725e-02, 4.97365510e-03,
        1.25014770e-03, 1.52155160e-04, 2.54408619e-03, 1.63810272e-02,
        2.35789630e-05, 2.16315597e-01, 1.22564770e-02, 2.81488377e-04,
        1.99324772e-04, 5.29644531e-05, 2.78307218e-02, 2.19113124e-03,
        2.73346814e-04, 2.55772502e-05, 1.81656539e-01, 3.65467034e-02,
        8.10353784e-04, 5.92541655e-05, 3.58508873e-06, 1.38711684e-07,
        2.19835638e-05, 9.96245220e-02, 2.22978052e-02, 3.95231982e-05,
        3.22165761e-05, 4.61705476e-02, 6.06859056e-03, 1.93082771e-04,
        5.33570255e-06, 1.09876214e-06, 1.62612832e-05, 9.50518698e-02,
        6.20285791e-05, 3.11516828e-06, 1.26692265e-01, 3.07644514e-04,
        8.10117945e-06, 4.97671181e-07, 2.90487078e-05, 4.66451719e-02,
        6.65847911e-04, 3.26533300e-05],
       [8.24494145e-06, 1.89094153e-05, 3.71399947e-05, 3.05986214e-06,
        1.98530711e-06,

In [ ]:
np.argmax(model.predict(X[:5]),axis=1)

array([13, 14, 15, 16, 18])

In [ ]:
# '대한' 다음 단어를 생성하려면
# '대한' => input모양에 맞게 변형
encoded=t.texts_to_sequences(['대한'])
print(encoded)
encoded=tf.keras.preprocessing.sequence.pad_sequences(encoded,maxlen=maxlen)
print(encoded)


[[5]]
[[0 0 0 0 0 0 5]]


In [ ]:
encoded

array([[0, 0, 0, 0, 0, 0, 5]], dtype=int32)

In [ ]:
result=model.predict(encoded)

In [ ]:
np.argmax(result,axis=1)

array([6])

In [ ]:
id_to_word[np.argmax(result,axis=1)[0]]

'사람'

In [ ]:
maxlen

7

In [ ]:
n=10
current_input='대한'

# result_str=''
result_str=current_input
for i in range(n):
    print(current_input)
    encoded=t.texts_to_sequences([current_input])
    encoded=tf.keras.preprocessing.sequence.pad_sequences(encoded,maxlen=maxlen-1)    
    print(encoded)

    result=model.predict(encoded)
    result_word=id_to_word[np.argmax(result, axis=1)[0]]
    result_str += ' ' + result_word
    current_input += ' ' + result_word

대한
[[0 0 0 0 0 5]]
대한 사람
[[0 0 0 0 5 6]]
대한 사람 대한으로
[[0 0 0 5 6 7]]
대한 사람 대한으로 길이
[[0 0 5 6 7 8]]
대한 사람 대한으로 길이 보전하세
[[0 5 6 7 8 9]]
대한 사람 대한으로 길이 보전하세 보전하세
[[5 6 7 8 9 9]]
대한 사람 대한으로 길이 보전하세 보전하세 보전하세
[[6 7 8 9 9 9]]
대한 사람 대한으로 길이 보전하세 보전하세 보전하세 보전하세
[[7 8 9 9 9 9]]
대한 사람 대한으로 길이 보전하세 보전하세 보전하세 보전하세 듯
[[ 8  9  9  9  9 27]]
대한 사람 대한으로 길이 보전하세 보전하세 보전하세 보전하세 듯 다하여
[[ 9  9  9  9 27 45]]


In [ ]:
result_str

'대한 사람 대한으로 길이 보전하세 보전하세 보전하세 보전하세 듯 다하여 없이'

In [ ]:
#함수화
def sentence_generation(model,t,current_input,n):
    result_str=current_input
    for i in range(n):
        encoded=t.texts_to_sequences([current_input])
        encoded=tf.keras.preprocessing.sequence.pad_sequences(encoded,maxlen=maxlen-1)    

        result=model.predict(encoded)
        result_word=id_to_word[np.argmax(result, axis=1)[0]]
        result_str += ' ' + result_word
        current_input += ' ' + result_word

    return result_str

In [ ]:
print(sentence_generation(model,t,'기상',n=4))

기상 삼천리 삼천리 화려 화려


In [ ]:
print(sentence_generation(model,t,'백두',n=4))

백두 삼천리 삼천리 화려 화려


In [ ]:
print(sentence_generation(model,t,'동해',n=7))

동해 물과 백두산이 마르고 닳도록 다하여 듯 듯


In [ ]:
print(sentence_generation(model,t,'하느님이',n=4))

하느님이 보우하사 우리나라 만세 만세


In [ ]:
print(sentence_generation(model,t,'만세',n=4))

만세 사람 사람 대한으로 보전하세


# seq2seq
- LSTM을 이용해 구현
- encoder,decoder

- 덧셈 데이터 구성
- encorder/decoder 정의
- 학습
- 평가(예측)

In [ ]:
#최대 세자리수끼리 합을 구하는 데이터

In [ ]:
import numpy as np

In [ ]:
# 99+1=>'9','9','+','1'

In [ ]:
num1=np.random.randint(0,1000)#0~999까지 수 중 랜덤생성
num2=np.random.randint(0,1000)

In [ ]:
ans=num1+num2

In [ ]:
num1,num2,ans

(585, 500, 1085)

In [ ]:
q_str=str(num1)+'+'+str(num2)
print(q_str)

55+934


In [ ]:
list(q_str)

['5', '5', '+', '9', '3', '4']

In [ ]:
word_to_id, id_to_word

In [ ]:
#1
word_to_id=dict([(str(key),value) for key,value in enumerate(range(10))])
#2
word_to_id={}
for key,value in enumerate(range(10)):
    word_to_id[str(key)]=value

In [ ]:
word_to_id

{'+': 10,
 '0': 0,
 '1': 1,
 '2': 2,
 '3': 3,
 '4': 4,
 '5': 5,
 '6': 6,
 '7': 7,
 '8': 8,
 '9': 9,
 '_': 11}

In [ ]:
word_to_id['+']=len(word_to_id)

In [ ]:
word_to_id['_']=len(word_to_id)

In [ ]:
#1
id_to_word=dict([(value,key) for key,value in word_to_id.items()])
#2
id_to_word={}
for key,value in word_to_id.items():
    id_to_word[value]=key

In [ ]:
id_to_word

{0: '0',
 1: '1',
 2: '2',
 3: '3',
 4: '4',
 5: '5',
 6: '6',
 7: '7',
 8: '8',
 9: '9',
 10: '+',
 11: '_'}

In [ ]:
#
def get_sum_dict():
    items=list(str(x) for x in range(10))
    items.append('_')
    items.append('+')

    id_to_item={}
    for idx,item in enumerate(items):
        id_to_item[idx]=item
    
    item_to_id =dict([(value,key) for key,value in id_to_item.items()])

    return id_to_item, item_to_id

id_to_item,item_to_id=get_sum_dict()

In [ ]:
def convert_item_to_id(items,item_to_id):
    ids=list([item_to_id[item] for item in items])
    return ids

def convert_id_to_item(ids,id_to_item):
    items=list([id_to_item[id] for id in ids])
    return items

In [ ]:
#x,y(label) 생성함수
def sum_data_gen():
    num1=np.random.randint(0,1000)
    num2=np.random.randint(0,1000)  
    ans=num1+num2
    q_str=str(num1)+'+'+str(num2)
    a_str='_'+str(ans).zfill(4) #4자리수로 맞춰라
    return list(q_str), list(a_str)

In [ ]:
sum_data_gen()[1]

['_', '1', '0', '1', '3']

In [ ]:
x,y=sum_data_gen()

In [ ]:
x,y

(['5', '4', '9', '+', '4', '2', '2'], ['_', '0', '9', '7', '1'])

In [ ]:
# convert_item_to_id()

In [ ]:
#만든 함수들을 활용해서 사용할 데이터셋을 생성 
def get_dataset(data_num=100):
    id_to_item,item_to_id = get_sum_dict()
    xs=[]
    ys=[]
    for i in range(data_num):
        x,y=sum_data_gen()
        xs.append(convert_item_to_id(x,item_to_id))
        ys.append(convert_item_to_id(y,item_to_id))
    
    return xs,ys


In [ ]:
get_dataset(data_num=10)

([[1, 7, 3, 11, 7],
  [1, 3, 1, 11, 9, 2, 0],
  [1, 9, 5, 11, 6, 7, 8],
  [9, 6, 3, 11, 4, 0, 6],
  [2, 6, 4, 11, 1, 5, 8],
  [5, 2, 0, 11, 6, 2, 9],
  [6, 5, 3, 11, 2, 8, 0],
  [3, 9, 7, 11, 9, 8, 4],
  [3, 7, 6, 11, 6, 1, 6],
  [8, 9, 0, 11, 6, 9, 9]],
 [[10, 0, 1, 8, 0],
  [10, 1, 0, 5, 1],
  [10, 0, 8, 7, 3],
  [10, 1, 3, 6, 9],
  [10, 0, 4, 2, 2],
  [10, 1, 1, 4, 9],
  [10, 0, 9, 3, 3],
  [10, 1, 3, 8, 1],
  [10, 0, 9, 9, 2],
  [10, 1, 5, 8, 9]])

In [ ]:
train_x, train_y = get_dataset(data_num=20000)
test_x, test_y = get_dataset(data_num=10000)
id_to_item, item_to_id = get_sum_dict()

In [ ]:
import tensorflow as tf

In [ ]:
from tensorflow.keras.layers import Input,LSTM,Embedding,Dense
from tensorflow.keras.models import Model,Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [ ]:
#숫자+문자1 라서 똑같은거지 번역(한글->영어)과 같은 경우에는 양쪽 사이즈가 다름
src_vocab_size=len(id_to_item)
tar_vocab_size=len(item_to_id)#id_to_item?
#one-hot인코딩할때 사용
# vocab_size=len(id_to_item)

In [ ]:
train_x = pad_sequences(train_x, maxlen=7, padding='pre')
test_x = pad_sequences(test_x, maxlen=7, padding='pre')
train_y = pad_sequences(train_y, maxlen=5, padding='pre')
test_y = pad_sequences(test_y, maxlen=5, padding='pre')

In [ ]:
train_y_t=train_y[:,1:]
test_y_t=test_y[:,1:]
train_y_t = pad_sequences(train_y_t, maxlen=5, padding='pre')
test_y_t = pad_sequences(test_y_t, maxlen=5, padding='pre')

In [ ]:
train_y_t.shape

(20000, 5)

In [ ]:
train_x = to_categorical(train_x, num_classes=vocab_size)
test_x = to_categorical(test_x, num_classes=vocab_size)
train_y = to_categorical(train_y, num_classes=vocab_size)
test_y = to_categorical(test_y, num_classes=vocab_size)
train_y_t= to_categorical(train_y_t, num_classes=vocab_size)
test_y_t= to_categorical(test_y_t, num_classes=vocab_size)

In [ ]:
train_x.shape, test_x.shape, train_y.shape, test_y.shape, train_y_t.shape, test_y_t.shape
# ((20000, 7, 12),
#  (10000, 7, 12),
#  (20000, 5, 12),
#  (10000, 5, 12),
#  (20000, 5, 12),
#  (10000, 5, 12))

((20000, 7, 12),
 (10000, 7, 12),
 (20000, 5, 12),
 (10000, 5, 12),
 (20000, 5, 12),
 (10000, 5, 12))

In [ ]:
# Encoder 
# encoder_input = Embedding(vocab_size, 5,  input_length=7)
encoder_inputs = Input(shape=(None, src_vocab_size))
encoder_lstm = LSTM(8, return_state=True)
encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)

encoder_states = [state_h, state_c]

In [ ]:
#Decoder
decoder_inputs=Input(shape=(None,tar_vocab_size))
decoder_lstm=LSTM(8,return_state=True,return_sequences=True)
#output,h,c자리인데 decoder의 h,c는 사용되지 않아서 _ 로
decoder_outputs, _,_=decoder_lstm(decoder_inputs,initial_state=encoder_states)

decoder_softmax_layer=Dense(tar_vocab_size,activation='softmax')
decoder_outputs=decoder_softmax_layer(decoder_outputs)

In [ ]:
#Model(input,output)
model =Model([encoder_inputs,decoder_inputs],decoder_outputs)

In [ ]:
model.summary()

Model: "functional_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, None, 12)]   0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, None, 12)]   0                                            
__________________________________________________________________________________________________
lstm (LSTM)                     [(None, 8), (None, 8 672         input_1[0][0]                    
__________________________________________________________________________________________________
lstm_1 (LSTM)                   [(None, None, 8), (N 672         input_2[0][0]                    
                                                                 lstm[0][1]            

In [ ]:
# train_x.shape, test_x.shape, 
# train_y.shape, test_y.shape,
# train_y_t.shape, test_y_t.shape

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(x=[train_x,train_y],
            y=train_y_t,
            batch_size=512,
            epochs=50,
            validation_split=0.2)

Epoch 1/50
32/32 [==============================] - 1s 27ms/step - loss: 2.4461 - accuracy: 0.2699 - val_loss: 2.3936 - val_accuracy: 0.3967
Epoch 2/50
32/32 [==============================] - 0s 6ms/step - loss: 2.3283 - accuracy: 0.3946 - val_loss: 2.2385 - val_accuracy: 0.3808
Epoch 3/50
32/32 [==============================] - 0s 6ms/step - loss: 2.1286 - accuracy: 0.3717 - val_loss: 2.0112 - val_accuracy: 0.3672
Epoch 4/50
32/32 [==============================] - 0s 6ms/step - loss: 1.9166 - accuracy: 0.3787 - val_loss: 1.8285 - val_accuracy: 0.3879
Epoch 5/50
32/32 [==============================] - 0s 6ms/step - loss: 1.7555 - accuracy: 0.4055 - val_loss: 1.6890 - val_accuracy: 0.4119
Epoch 6/50
32/32 [==============================] - 0s 6ms/step - loss: 1.6303 - accuracy: 0.4223 - val_loss: 1.5731 - val_accuracy: 0.4315
Epoch 7/50
32/32 [==============================] - 0s 6ms/step - loss: 1.5171 - accuracy: 0.4565 - val_loss: 1.4606 - val_accuracy: 0.5217
Epoch 8/50
32/32 [=